### ISSUE TITLE
`@changesets/cli` should be a dev dependency

### ISSUE THREAD

**Issue by billyjanitsch** [yaacovCR/value-or-promise#1]
Currently, it's a production dependency, which means that it's installed in every project that depends on `value-or-promise`. I'm guessing this is an oversight as it doesn't seem to be used other than as a dev tool.

**Comment by paulrostorp** [comment]
This package was added to my dependency tree because I'm using graphql tools and it was added by this https://github.com/ardatan/graphql-tools/pull/2871

`@changesets/cli` breaks my linting config by adding prettier@v1 to my dependency tree...

Please fix 😃

**Comment by yaacovCR** [comment]
Whoops. Will do

**Comment by yaacovCR** [comment]
Done in v1.0.6

**Comment by mymywang** [comment]
Hi @yaacovCR My team is also blocked by this. Is v1.0.6 already released? I can't find the updated version and the fix. Could you link the fix here? Thank you.

**Comment by billyjanitsch** [comment]
@mymywang 1.0.6 was [published to npm](https://www.npmjs.com/package/value-or-promise/v/1.0.6) (and includes this dependency change) but it doesn't appear to have been pushed to GitHub.

**Comment by yaacovCR** [comment]
v1.0.7 released and now pushed as well. Exciting times. I wish changesets actually worked with npm 7 and yarn...

**Comment by zhamujun** [comment]
Verified. It's [released in v1.0.6](https://github.com/yaacovCR/value-or-promise/blob/b5b150fba036f2839fdb64827a373e0753066c9a/package.json#L29)
